name: PR Review Copilot

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write   # needed to post a comment

jobs:
  summarize-and-comment:
    runs-on: ubuntu-latest
    env:
      HF_HOME: ${{ github.workspace }}/.hf_cache
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need the base commit for diff

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers torch requests

      - name: Run PR Review Copilot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python src/pr_review_copilot.py
